### ISSUE TITLE
DMCA Takedown Notice

### ISSUE THREAD

**Issue by LucioPelinson** [JJConsulting/sap-web-ide-tutorial#1]
Hi, @mmarkvillanueva @jjconsulting
I don't want to disturb you, but this organization (JJConsulting) already has been registered.
This name is very important for us, can you rename or delete it?

thanks,

**Comment by mmarkvillanueva** [comment]
i-renamed the Org. this is just for testing purposes and I don't have any intention to really use someone else org name.
